name: Deploy to ECS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin 891377228113.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t flask-app .
          docker tag flask-app:latest 891377228113.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flask-repo-1623064:latest
          docker push 891377228113.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flask-repo-1623064:latest

      - name: Deploy to ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service --cluster flask-cluster-1623064 \
            --service flask-service-1623064 \
            --force-new-deployment --region $AWS_REGION
